fail_fast: false
repos:
  - repo: local
    hooks:
      # * lib
      # ** python
      # *** fastapi_exceptions
      - id: fastapi_exceptions-pyflakes
        name: Format Lint Test
        pass_filenames: false
        language: system
        entry: bash -c 'pytest -s'