version: "3.7"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./realms:/opt/keycloak/data/import
    ports:
      - 8080:8080
    command:
      - start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
      - VIRTUAL_PORT=8080
      - KC_HOSTNAME=keycloak
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_PASSWORD=changeme
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo:6.0.9
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  minio:
    ports:
      - '9000:9000'
      - '9001:9001'
    image: 'bitnami/minio:2024.3.5'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_NOTIFY_KAFKA_ENABLE_COFFEE=on
      - MINIO_NOTIFY_KAFKA_BROKERS_COFFEE=kafka:9092
      - MINIO_NOTIFY_KAFKA_TOPIC_COFFEE=coffee-images
  minio-mc:
    image: 'bitnami/minio-client'
    depends_on:
      - minio
      - kafka
    entrypoint:
      - /bin/sh
      - -c
      - |
        sleep 20
        mc alias set minio http://minio:9000 minio-root-user minio-root-password
        mc mb minio/coffee-images
        mc event add minio/coffee-images arn:minio:sqs::COFFEE:kafka --event "put,delete" --prefix **/original/
  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
  backend:
    image: weastur/poetry:1.8.3-python-3.11
    depends_on:
      - mongo
    volumes:
      - "${BACKEND_PATH}:/app"
    working_dir: /app
    command: sh -c "poetry install && poetry run python3 -m coffee_backend"
    ports:
      - 8000:8000
    environment:
      - "KEYKLOAK_HOST=keycloak:8080"
      - "KEYCLOAK_ISSUER_HOST=keycloak:8080"
      - "UVICORN_RELOAD=True"
  frontend:
    image: docker.io/node:19.4.0
    volumes:
      - "${FRONTEND_PATH}:/app"
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - 5173:5173
  resizer:
    image: weastur/poetry:1.8.3-python-3.11
    depends_on:
      - kafka
    volumes:
      - "${RESIZER_PATH}:/app"
    working_dir: /app
    command: sh -c "poetry install && poetry run python3 -m resize"


volumes:
  postgres_data:
